### ISSUE TITLE
Alternative to Hardware Configuration

### ISSUE THREAD

**Issue by ErikS-web** [nicsure/QuanshengDock#12]
That microphone has an earplug at the bottom.

The radio audio also comes from there. You do have 2 cables to your microphone, but it is just as easy to make.

Possibly add a resistor internally and possibly also a capacitor due to DC voltage from the UVK5(8) on the audio-signal

![Easier way to connect](https://github.com/nicsure/QuanshengDock/assets/148579604/d93be3d6-0dff-43a6-b60a-229b00e1a29a)

**Comment by ErikS-web** [comment]
An Y-cable for 3.5 is easy to find at Ali....

Any suggestions for the 2.5 mm Y-cable ?

**Comment by nicsure** [comment]
Well throw me in a bucket of custard. I had NO IDEA the microphone had a ear port on the bottom. LOL!

**Comment by ludwich66** [comment]
I had opened this kind of handset - a draft picture

<img width="358" alt="image" src="https://github.com/nicsure/QuanshengDock/assets/12202733/5d364382-04d1-4602-bdc7-de371932fc58">

**Comment by ludwich66** [comment]
Please Verifiy and Comment Schematic:
There is Version A (First Cable connection) and
Version B (Connect Soundcard over Special-Cable to External-Handset

<img width="800" alt="image" src="https://github.com/nicsure/QuanshengDock/assets/12202733/c2647961-7a22-4dbc-9cdf-6653000f29a0">

**Comment by ludwich66** [comment]
Please check this Schematic:
Version 1 : Old QS-Dock-Cable
Version2 : Connection over Handset-Earphone-Connector
<img width="800" alt="image" src="https://github.com/nicsure/QuanshengDock/assets/12202733/62843da4-f900-4e95-a724-2ca3443c48ad">

**Comment by ErikS-web** [comment]
Another idea: 

You can also use _a second 2.5 mm Y-cable_/Split cable to split the audio to the PC.

And then insert the resistor into the 2.5mm plug

**Comment by ludwich66** [comment]
<img width="264" alt="image" src="https://github.com/nicsure/QuanshengDock/assets/12202733/55bb4211-874e-4045-bc1c-2f68beefdf7a">

**Comment by ErikS-web** [comment]
Where to buy in 2.5 mm ?
