### ISSUE TITLE
Idea:  *** Memory Channel Scan ***

### ISSUE THREAD

**Issue by ErikS-web** [nicsure/QuanshengDock#14]
Not because it has to be, but because it might be possible ;-)

In addition to the Frequency spectrum scan, Kamilss has also made a Memory scan in his firmware-project.

Now I thought, that might also be possible here. But just a little different. With all the load on the PC-program.

My idea ...

- First use the build-in channel editor to load the memory channels to pc and
- Than Select the "New Function" Memory Channel Scan
- To make it perfect. Add the selection to scan All, List-1 and List-2.

**Comment by nicsure** [comment]
I was planning on this yes. Also wanted to add a channel store on the application side so we can overcome the 200 limit. Also planning a "Free VFO" mode. This essentially takes full control of the radio and gives you a jog wheel etc..

**Comment by ErikS-web** [comment]
It has been realized in an even more beautiful version.
In latest release [0.31.5w Complied Binaries](https://github.com/nicsure/QuanshengDock/releases/tag/0.31.5w)

You can define various scan groups on the PC.
