### ISSUE TITLE
[Interface] AIOC cable

### ISSUE THREAD

**Issue by magellan-13016** [nicsure/QuanshengDock#17]
Hi,

I've bought the AIOC (All In One Cable) Adapter Kit For Ham Radio Baofeng & Quansheng pockets transceivers.

purchase link : [https://www.ebay.com/itm/186077832070](url)

Github repository : [https://github.com/skuep/AIOC](url)

Is this interface supported by the control software ? 

This would be a nice solution to control the transceiver without microphone and loudspeaker switched off.

David (F4BPP).

**Comment by nicsure** [comment]
When I get mine I'll be able to give some advice. From all reports and what I've researched it does look like it will be compatible.

**Comment by magellan-13016** [comment]
Wonderful !

**Comment by ErikS-web** [comment]
Do a search on AIOC and you will find .... #8 and #6

Also... pse _**Use titles that make sense**_

Suggest Issue-starter to close this issue.

**Comment by jhenkins** [comment]
Hi,

Hayden from the "Ham Radio DX" Youtube channel has successfully used this project with his AIOC cable:

https://www.youtube.com/watch?v=vgVocQpSF7s

Let's call it a "match made in heaven"! :-)

**Comment by nicsure** [comment]
I also have managed to hack together a bluetooth programmer and a bluetooth audio sender. It's a bit of a mess but I can now do everything over bluetooth, meaning I can have the radio in the other room, or in the loft or wherever.

**Comment by ErikS-web** [comment]
This seems to work and is now [documented in the Wiki under Connections](https://github.com/nicsure/QuanshengDock/wiki/30-%E2%80%90-Connection-between-radio-and-PC#aioc-cable)

**Comment by ErikS-web** [comment]
@magellan-13016 Did you manage to get it working?

**Comment by ErikS-web** [comment]
Nicsure tested himself and made an nice vidio with installation-tips.

**_AIOC Configuration_** for Quansheng Dock (date: 05-02-2024) [Link ](https://www.youtube.com/watch?v=IrnzWVdOlu8)
