### ISSUE TITLE
The Settings does not provide specific Settings for the XFO.

### ISSUE THREAD

**Issue by ErikS-web** [nicsure/QuanshengDock#18]
XVFO, very nice. **My QS now has two dials.** One on the QS and the 2nd on the PC.

When XFO-selected. The Settings does not provide specific Settings for the XFO.
It is not clear to me how to define the starting frequency and squelch value

Tip. If I read the memory channels first. It would be nice to put the memory name on the screen if the frequency is recognized. As Kamilsss does in his Specrum memory scan

**Comment by nicsure** [comment]
The settings are general, colors and serial port/audio etc.. They're not really specific to anything.

The problem there is that multiple channels may have the same frequency. Plus there's an overhead having to search 200 channels everytime the monitor kicks in. But I'll see what can be done.
