### ISSUE TITLE
XFO idea : Add cursor control also to control VFO

### ISSUE THREAD

**Issue by ErikS-web** [nicsure/QuanshengDock#19]
Why only rotating knob ?

Consider to add cursor-control as well

VFO-STEP-UP = cursor-Up or cursor-Right or rotate-Right
VFO-STEP-DOWN = cursor-Down or cursor-Right or rotate-Left

I suggest Cursor-control from key-board, but perhabs also interesting to add it as onscreen buttons UP/DOWN

**Comment by ErikS-web** [comment]
Or + and - on the keyboard

**Comment by nicsure** [comment]
There's already keyboard routines in place, I can add key binding for that easily enough.

**Comment by ErikS-web** [comment]
Arrow-keys now works. 👍 
When **_the mousr cursor is above VFO-wheel,_** the scroll-wheel of the mouse also work 👍
