### ISSUE TITLE
Change Language

### ISSUE THREAD

**Issue by Conny64** [nicsure/QuanshengDock#22]
how can I change the language?

**Comment by nicsure** [comment]
I only speak English. Sorry.

**Comment by nicsure** [comment]
They're just what the compiler generates for multi-language support, but I haven't implemented multi-language yet. I plan to release a literals file at some point so people can make translation packs. But just being an English speaker it's not something I can do. I can use translators of course, but they're sketchy at best.

**Comment by Conny64** [comment]
Thanks for the info. If you want to make it multilingual, I can help you translate it into German.

**Comment by nicsure** [comment]
Thanks, I have so many things to do that it might be a while. But at that stage it will simply be a matter of taking a text file in the install, it will have lines of text in it in English, these just need to be translated to whatever language and submitted back to me. 

Again thanks for your support.

**Comment by Conny64** [comment]
Don't worry, when you have finished the file just get in touch with me.

**Comment by ErikS-web** [comment]
Can be closed for now
