### ISSUE TITLE
Add FN-1 to userinterface [request]

### ISSUE THREAD

**Issue by ErikS-web** [nicsure/QuanshengDock#26]
In the user interface, the **Side Button II (FN2)** is located under the **Lamp-key.**

What is missing is **FN1**. Can it also be fitted in somewhere?

**_Why._** Because both keys are user-programmable in the menu of radio-firmware  (F1Shrt, F1Long, F2Shrt, F2Long)

![FN-1 and FN-2](https://github.com/nicsure/QuanshengDock/assets/148579604/ed02bf31-f53d-48f9-922d-f1fb83b6ceb5)

**Comment by nicsure** [comment]
Both of those are already implemented. The buttons are SQL and the 💡 . This was all explained in the first video.
