### ISSUE TITLE
Use WIKI for documentation of QS-Dock  [request] 

### ISSUE THREAD

**Issue by ErikS-web** [nicsure/QuanshengDock#27]
Now there is so much functionality in Dock....

Suggest to activate the Wiki as Online documentation.

I can provide `extra hands`

**Comment by nicsure** [comment]
I enabled the Wiki in the settings. Not sure what to do now though.

**Comment by ludwich66** [comment]
or see  https://github.com/ludwich66/Quansheng_UV-K5_Wiki/wiki/Quansheng%E2%80%90Dock
Is this Part OK of you? 
Plaese check Schematik.

Greatings ludwich

**Comment by nicsure** [comment]
Looks good. You should be able to edit this wiki as I've enabled public editing. I'll figure out how to add you as collab if you want?

**Comment by ErikS-web** [comment]
Ok, had some brainstorming, and made an index as initial setup.
Will continue in next days. As I am also working on Kamilsss Wiki

Feel free to help. Lets communicatie via Telegram.

**Comment by ErikS-web** [comment]
@ludwich66  / Ludwich

You could also include my "Alternative to Hardware Configuration" see picture in #12.

**Comment by ErikS-web** [comment]
[Wiki is under construction ](https://github.com/nicsure/QuanshengDock/wiki)

**Comment by ErikS-web** [comment]
This can be closed
