### ISSUE TITLE
Radio firmware 0.31.1q CRC CHECK FAILED! FIRMWARE NOT VALID! in UVTOOLS-link [BUG]

### ISSUE THREAD

**Issue by ErikS-web** [nicsure/QuanshengDock#28]
In README.md section of radio firmware
https://github.com/nicsure/quansheng-dock-fw?tab=readme-ov-file#requires-quansheng-dock-v0313q

erro when trying to flash via UVTOOLS

_Loading file from url: https://github.com/nicsure/quansheng-dock-fw/releases/tag/0.31.1q/firmware.packed.bin

WARNING: **CRC CHECK FAILED! FIRMWARE NOT VALID!**
Make sure to choose a flashable bin file. 
Error while loading firmware, check log above or developer console for details._

Link should be

https://egzumer.github.io/uvtools/?firmwareURL=https://github.com/nicsure/quansheng-dock-fw/releases/download/0.31.1q/firmware.packed.bin

**Comment by nicsure** [comment]
I just got the URL wrong in the link, is fixed now.

**Comment by ErikS-web** [comment]
Suggest to add text [🗲FLASH WITH A BROWSER🗲](https://egzumer.github.io/uvtools/?firmwareURL=https://github.com/nicsure/quansheng-dock-fw/releases/download/0.31.1q/firmware.packed.bin) in the README.md

**Comment by ErikS-web** [comment]
OK, fixed
