### ISSUE TITLE
Is a Linux/MacOs (so basically Unix) version planned in the Future?

### ISSUE THREAD

**Issue by Rebell64** [nicsure/QuanshengDock#3]
Just because a bigger than normal Portion of People in the HAM-Radio Hobby use (sometimes exclusively) Linux (or other Unix-like).

**Comment by nicsure** [comment]
Yes, this is just my initial release I am planning to port to other platforms.

**Comment by om0wt** [comment]
Hello,

```https://docs.avaloniaui.net``` should be the way...
