### ISSUE TITLE
Cant Start the new 0.31.3

### ISSUE THREAD

**Issue by Blinky122** [nicsure/QuanshengDock#32]
Hello,
when i will start the new version. i become this issue

![issue quasheng dock](https://github.com/nicsure/QuanshengDock/assets/91134937/9b43dffa-1e77-4143-8ba8-75485f3de280)

**Comment by ErikS-web** [comment]
What operating system and version ?

Did you use the latest release [0.31.3q](https://github.com/nicsure/QuanshengDock/releases/tag/0.31.3q) ?

**Comment by nicsure** [comment]
There are some config changes, It looks like I didn't handle some conversion from the older format. Clearing the app's config might work. Config is stored in the User Documents folder.

**Comment by ErikS-web** [comment]
Suggest to update to latest release of [QuanshengDock](https://github.com/nicsure/QuanshengDock/releases)

and the [latest Firmware for radio]( https://github.com/nicsure/quansheng-dock-fw/releases)
