### ISSUE TITLE
[XVFO] Dots and Comma`s ? How2 enter frequency

### ISSUE THREAD

**Issue by ErikS-web** [nicsure/QuanshengDock#35]
Initial screen

![Afbeelding1](https://github.com/nicsure/QuanshengDock/assets/148579604/ba599035-37ba-4852-8a50-53cf7ca4929d)

Switch to VFO
 
![Afbeelding2](https://github.com/nicsure/QuanshengDock/assets/148579604/1b71b8a9-5f6f-4cfb-8651-fcec3596229b)

XVFO
Starts with Comma in frequency

![Afbeelding3](https://github.com/nicsure/QuanshengDock/assets/148579604/7bee071d-a1c6-413d-8c30-e407851ddeed)

 
With DOCK-keyboard&Mouse type 145.000
 
![Afbeelding4](https://github.com/nicsure/QuanshengDock/assets/148579604/620c06ea-ffb9-4d89-9868-7ac651eb736d)

ENTER
GIVES 1300,00000
 
![Afbeelding5](https://github.com/nicsure/QuanshengDock/assets/148579604/0fa0da80-44f7-4805-9b4e-82dd95fe74fa)

145 Enter gives

 
![Afbeelding6](https://github.com/nicsure/QuanshengDock/assets/148579604/abf43fcb-fbd6-4e98-bb11-cdd4a563507b)

145.4 on **Numeric part of keyboard**
 
![Afbeelding8](https://github.com/nicsure/QuanshengDock/assets/148579604/b1a103a3-4589-4acf-8b33-f3dc53983dce)

ENTER
Gives

![Afbeelding9](https://github.com/nicsure/QuanshengDock/assets/148579604/b0bc2db1-8e1a-481b-bf92-d517ef813b75)

Actual Dock and firmware. See printscreens
Windows 10, with US-Int keyboard and NLD-settings of windows

**Comment by nicsure** [comment]
Must be something to do with language settings in windows, all mine are just dots I don't get commas.

**Comment by nicsure** [comment]
It looks to be ignoring the "." and thinks you're entering 1454 so it's clamping it to 1300. What happens if you enter "145,4" with a comma ?

**Comment by nicsure** [comment]
Also try clicking on the frequency and then editing it. From what I can tell it has something to do with the way C# converts text to numbers and it is different depending on how Windows is setup language wise.

**Comment by nicsure** [comment]
https://github.com/nicsure/QuanshengDock/releases/tag/0.31.8d

See how that works. It's hard for me to test as I don't have my PC setup for that language mode.

**Comment by ErikS-web** [comment]
Dot and Comma’s part-2

Intital screen with DOT
![Afbeelding1](https://github.com/nicsure/QuanshengDock/assets/148579604/69e4e424-19e2-48ab-b43b-75d7c345be9e)

Selecting XFO ...  XFO screen with Comma
![Afbeelding2](https://github.com/nicsure/QuanshengDock/assets/148579604/7cc185cd-aa94-4d42-972e-9b50961da807)
 
And strange stations in memory schannels (mentioned/had this problem earlier)
Turning VFO give error: Out of Range
 
![Afbeelding3](https://github.com/nicsure/QuanshengDock/assets/148579604/474197a7-eaa9-47ab-855b-685a4254c4bb)

Restarting Application
and press **Spect**
 
![Afbeelding4](https://github.com/nicsure/QuanshengDock/assets/148579604/b230d296-0532-4ed2-8607-61fb6ea4e594)

Left DOT and Right Comma ????
Press **Analyser**
Now all Comma’s
 
![Afbeelding5](https://github.com/nicsure/QuanshengDock/assets/148579604/b8ee082a-6e3d-4efc-9365-eaf3dac6133c)


The Numeric-keyboard “.” Is not accepted.
I have to use the Comma (On ASCII-keyboard To the right of M-key)
The “.”(dot) net to “,”(comma) is also not accepted

 
![Afbeelding6](https://github.com/nicsure/QuanshengDock/assets/148579604/160f9cf0-de52-423e-afe4-c44192dfa020)

**Comment by ErikS-web** [comment]
Communication with the radio is also disrupted after a crash.
Then I have to power the radio off and on.

Is there some control on radio communication, such as a check-sum? That could make communication with the radio more stable.

**Comment by nicsure** [comment]
You've got some corrupted config data, you have ??? for the mode and 25 for the bandwidth, something is seriously messed up in the app's saved config

**Comment by ErikS-web** [comment]
Suggest to test the latest release [0.32.6q](https://github.com/nicsure/QuanshengDock/releases/tag/0.32.6q)

I am happy ;-)

**Comment by ErikS-web** [comment]
![4](https://github.com/nicsure/QuanshengDock/assets/148579604/e6c740cf-ea1e-44ac-9a2a-ef0af4367712)

I finally can close this ISSUE. 

**_Thanks for solving it_**. 👍 01
