### ISSUE TITLE
[XVFO] Stepsize change, does not round the frequency to stepsize

### ISSUE THREAD

**Issue by ErikS-web** [nicsure/QuanshengDock#36]
Would prefer it does.

Because why else change the stepsize ?

At least when you manually increase the step size, and then rotate the button.

**Comment by nicsure** [comment]
That's what the "Quantize" option in the right click menu of the jog wheel does.

**Comment by nicsure** [comment]
Oh, actually, that option is supposed to toggle and it's also supposed to be default to on. I'll look at that now, it's not behaving like it's supposed to do.

**Comment by nicsure** [comment]
Should be fixed in next release.

**Comment by ErikS-web** [comment]
Yes it does, already in [preview 8](https://github.com/nicsure/QuanshengDock/releases/tag/0.31.8d) 👍

**Comment by ErikS-web** [comment]
Also works fine in Initial Screen 👍

**Comment by ErikS-web** [comment]
Thanks.
