### ISSUE TITLE
What - where is the editor?

### ISSUE THREAD

**Issue by TavaDelphin** [nicsure/QuanshengDock#41]
To add a group of memory or preset entries seems to be possible using the import selection in the drop-down in the presets screen. The choice is to Import from the editor - All or Update.

What editor is referenced and where might it be?

What file format should be used to build a file externally - straight .csv does not seem to work.

Thank you again for all the hard work and great value you are adding to the radio.

**Comment by nicsure** [comment]
It imports from the channel editor on the main interface.
Use the channel editor as normal to read the radio or load from a saved channel file.
Then go to the XVFO and select All to pull all your channels from the Channel Editor into the XVFO
Update is used to compare the channels in the XVFO against the ones in the Channel Editor and apply any differences.
