### ISSUE TITLE
XVFO missing under 0.32.4q

### ISSUE THREAD

**Issue by SigmazGFX** [nicsure/QuanshengDock#42]
Fired up 0.32.4q in VS2022 and the XVFO seems to be button is missing.

**Comment by nicsure** [comment]
Hmmm, I commit to an intermediate private repository so I can stage version commits in one go rather a bunch of small ones. Seems that has been broken for a while and isn't committing to the main branch. Thanks for bringing that to my attention.

**Comment by ErikS-web** [comment]
Suggest to test the latest release [0.32.6q](https://github.com/nicsure/QuanshengDock/releases/tag/0.32.6q)
![Knipsel](https://github.com/nicsure/QuanshengDock/assets/148579604/89245884-eb2a-46b1-b323-d49817ff87c4)

**Comment by SigmazGFX** [comment]
The issue with the release method appears to have been fixed. 
Thanks
