### ISSUE TITLE
[FEATURE] Select bar stops scanning and listen to that frequency

### ISSUE THREAD

**Issue by ErikS-web** [nicsure/QuanshengDock#45]
QS-Dock version 0.32.8x. XVFO-scan

_When selecting a bar in the spectrum-view;_ **_STOP scanning and tune in_** on selected bar-frequncy and display frequency and channel name.

Continue scanning when nothing is received.

**Comment by nicsure** [comment]
Yes, good suggestion.

**Comment by nicsure** [comment]
Implemented

**Comment by ErikS-web** [comment]
Beautifully realized in new release [0.32.11q](https://github.com/nicsure/QuanshengDock/releases/tag/0.32.11q)

![Beluisteren PI3UTR](https://github.com/nicsure/QuanshengDock/assets/148579604/ff50364e-4d89-41fa-b0a5-f1e11df17210)

Thank you 👍
