### ISSUE TITLE
[FEATURE] Add received channel info on screen in XVFO-scan

### ISSUE THREAD

**Issue by ErikS-web** [nicsure/QuanshengDock#46]
QS-Dock version 0.32.8x, XVFO, SCAN

Now the text is "Scanning list ..." or Channel info when mouse on selected channel,

**Situation** 
During scan a station is detected and this is drawed with colour. 

**Feature-request**
Is it posible to add the Frequency and Channelname on display as long as monitor is receiving om that frequency ?

And what can be **_follwo-up actions_**....
SPACE-bar: stop scanning and stay on this frequency
Right arrow: Continue scanning directly
Left arrow: Reverse scanning (if possible)

**Comment by nicsure** [comment]
The frequency and channel name is displayed on the main XVFO window, do you mean duplicate that in the scan window?

**Comment by ErikS-web** [comment]
YEs but ONLY when signal is received.

**Comment by nicsure** [comment]
So, for example. Where "Scanning List Whatever.." is displayed in the scan window, when monitor is engaged (either manually or automatically) this changes to something like "Monitoring <channel name> on <channel frequency>"

**Comment by ErikS-web** [comment]
![Knipsel](https://github.com/nicsure/QuanshengDock/assets/148579604/161bbe4f-9c3b-48a1-9e42-11e017afa678)

p.s. of course not the white background.

**Comment by nicsure** [comment]
Implemented

**Comment by ErikS-web** [comment]
Beautifully realized in new release [0.32.11q](https://github.com/nicsure/QuanshengDock/releases/tag/0.32.11q)
 
![Listening to PI3UTR](https://github.com/nicsure/QuanshengDock/assets/148579604/b381f2fe-cfd1-4fea-92a2-bb8599094e81)


Thank you 🥇
