### ISSUE TITLE
[BUG] In XVFO only PTT on PC-screen works and not (external) PTT

### ISSUE THREAD

**Issue by ErikS-web** [nicsure/QuanshengDock#47]
QS-Dock version 0.32.8x. XVFO-scan

On first screen the PTT of my (external) microphone works. 

But with XVFO only PTT on PC-screen works.
When I exit back to first screen it take about 3 to 4 seconds before PTT of my external microphone works again.
Reaction on Internal PTT of radio is same as External PTT.

**Comment by nicsure** [comment]
It's impossible for external PTT to work with the XVFO, the reason is because the physical PTT switch cuts off the serial RX data and that is required for the XVFO to function.

**Comment by ErikS-web** [comment]
Yes that the reason. I will mention it on the Wiki
