### ISSUE TITLE
[BUG] Transmitting on AIR-band frequencies is possible

### ISSUE THREAD

**Issue by ErikS-web** [nicsure/QuanshengDock#48]
PSE Disable.

**Comment by nicsure** [comment]
Oh, that's an old experimental thing. When in AM mode it attempts to modulate the power with the mic audio to accomplish AM transmission.

**Comment by ErikS-web** [comment]
If you would like to continue TX (of FM) in Airband. Than I suggest to set power always to (almost) minimum.
And not...
![Airband-TX](https://github.com/nicsure/QuanshengDock/assets/148579604/c3ac855c-af5c-41b3-9f20-a1c013aed879)

**Comment by nicsure** [comment]
The XVFO has no concept of bands or modes when it comes to TX, whatever frequency or mode you're in TX is always allowed. Basically, there's no restriction on TX at all.

**Comment by nicsure** [comment]
I've added an option in settings to disable TX on non-FM modes.
