### ISSUE TITLE
[Question] What is the format of an .CHAN-file

### ISSUE THREAD

**Issue by ErikS-web** [nicsure/QuanshengDock#49]
I would like to make different channelfiles to load, for different use of scanning.
HAM, AIR-band, PMR, LPD, etc
But in what format/syntax ?

**Comment by nicsure** [comment]
It's just a binary dump of areas of the radio's eeprom

**Comment by ErikS-web** [comment]
How2 prepare a frequency list (with parameters) to add to the XFO-scan.

Else than Import from Editor or manually.

I would like to test a big/long frequency list

**Comment by nicsure** [comment]
I'll work on a batch editor for the XVFO channels, I was planning on that anyway.

**Comment by nicsure** [comment]
The .CHAN files don't really have a format as they're just an image of the radio's memory. So I'm closing this.

**Comment by nicsure** [comment]
Not really answerable.
