### ISSUE TITLE
[FEATURE] PAUSE button to the XVFO channel scan

### ISSUE THREAD

**Issue by ErikS-web** [nicsure/QuanshengDock#50]
Please add a PAUSE button (or keyboard Key) to the XVFO channel scan, so you can stay on that channel and listen and sometime later just continue scanning.

p.s. Pressing SPACE stops the scanning.

**Comment by nicsure** [comment]
Pressing "Esc" stops scanning.

**Comment by nicsure** [comment]
The best option here would be to just use "Stop" and "Start" and I just make the scan resume from where it was stopped, that would effectively then be the same as pausing. I can't use Space to do this, but I could assign Start/Stop to another key, maybe Return?

**Comment by ErikS-web** [comment]
ESC, aha. I'll put it on the Wiki.

And Enter as a HALT/Continue would be nice.

**Comment by nicsure** [comment]
Mabaged to do it with "Space" after all.

**Comment by ErikS-web** [comment]
Tested and enjoyed even more release **0.32.14q**
**with**
### **_Better bar-graph plotting for scan RANGEs._**

That looks perfect... 👍  💯 
see here below.
![Knipsel](https://github.com/nicsure/QuanshengDock/assets/148579604/a0ea0692-e4e3-4d19-b9c0-3b898abbb130)
