### ISSUE TITLE
[Feature] XVFO: ideas for Keyboard key-assignment

### ISSUE THREAD

**Issue by ErikS-web** [nicsure/QuanshengDock#52]
Suggest 

`F` set Mode FM.  `f` for FM- narrow and `F` for FM-wide
`M` of `m` for max Mic Gain (100%)
`P` or `p` for vary Power 
`Q` of `q` for toggle sQuelch open
`T`or `t` for transmit 1750 Khz

**Comment by nicsure** [comment]
I can set F to toggle between FM Wide and FM Narrow, but F is just F there's no distinction between upper and lower case.
M is already used to toggle through modes, suggest another key for that.
Power on P will be in next release.
Squelch on Q will be in next release.
T I'm not sure about, do you mean transmit a 1750Hz tone?

**Comment by ErikS-web** [comment]
`F` as a quick key to go2 FM-wide and than toggle Wide/Narrow

`M` is indeed already in use and I mentioned it on the [key-assignment on the Wiki](https://github.com/nicsure/QuanshengDock/wiki/50-%E2%80%90-Specific-Functions-explained#keyboard-key-assignment)
Perhabs use `G`ain or `V`oice

P and Q nice 

`T` indeed to perform the 1750 Hz tone

**Comment by nicsure** [comment]
In next release :
F = FM Wide/Narrow toggle.
G = Mic gain
S = Toggle squelch mode, (same function as clicking the button)

Need to work on T bear with me.

**Comment by ErikS-web** [comment]
Suggest ... just like DTMF active and pressing (numeric) keys..

**Comment by ErikS-web** [comment]
Next release will have extra keys ... already mentioned in the [Online manual](https://github.com/nicsure/QuanshengDock/wiki/50-%E2%80%90-Specific-Functions-explained#next-release-will-have)

**Comment by ErikS-web** [comment]
Q or S for sQuelch ?

**Comment by nicsure** [comment]
Q is the same as clicking Open to open the squelch.
S is the same as clicking Squelch to change the squelch setting.

**Comment by nicsure** [comment]
All done, managed to get T to send a 1 second 1750Hz tone when pressed during transmit.

**Comment by ErikS-web** [comment]
Nice, but why can GAIN not set to 100% (Is now from 0 .. 96%)

Suggest to toggle to MAX (100%) and NOT rotate back from 0

**Comment by nicsure** [comment]
Well I'm sorry I can't do everything exactly as you suggest, the difference between 100% and 96% is not even humanly noticeable.

**Comment by ErikS-web** [comment]
Well,  I think to hear it is somewhat stronger audio signal at 100%.
And do not have any reason to start from 0.

At all my radio's I have to set Menu.31 `Mic` to MAX value +15.1dB to be able to have good volume with external microphone.

**Comment by ErikS-web** [comment]
Editing the Wike now with latest release.

How2 explain SQ-1... -4 ? 
So I user SQ-R in combination with "Bar". Or how do you call that ?

Selecting these item don't show anything changing on my screen

**Comment by ErikS-web** [comment]
See the temporary label: 
https://github.com/nicsure/QuanshengDock/wiki/50-%E2%80%90-Specific-Functions-explained#next-release-will-have-03216q

**Comment by ErikS-web** [comment]
Above mentioned Temporary label removed.

All keys now here [keyboard-key-assignment](https://github.com/nicsure/QuanshengDock/wiki/50-%E2%80%90-Specific-Functions-explained/_edit#keyboard-key-assignment).

Could you verify ?

**Comment by nicsure** [comment]
Keys look good.

**Comment by ErikS-web** [comment]
Thanks to user **GikaH** for additional feedback
