### ISSUE TITLE
[Feature]XVFO-scanner: Presets In List: reorder channels

### ISSUE THREAD

**Issue by ErikS-web** [nicsure/QuanshengDock#56]
Would like the option to reorder the channels/frequencies (UP/DOWN)

**Comment by nicsure** [comment]
You can do that in the right click menu, also better options to arrange xvfo channels will be in the channel manager when it's ready/

**Comment by ErikS-web** [comment]
Yes in the channellist in the XVFO-screen.

But see title....

But not (yet) in the screen _XVFO-scanner_: **Presets In List**

**Comment by nicsure** [comment]
Oh the scanner, sorry, yesm like a move up/down? Okay.

**Comment by ErikS-web** [comment]
Yes

**Comment by nicsure** [comment]
Done, also made the list colour scheme follow the LCD colour settings.

**Comment by ErikS-web** [comment]
2 x beautifull ;-)

Work fine 👍 

So next idea is #57
