### ISSUE TITLE
PTT not working with AIOC

### ISSUE THREAD

**Issue by tristanmoney** [nicsure/QuanshengDock#6]
Really neat software, but PTT doesn't seem to work with a AIOC. Everything else works though.

I think the AIOC is the perfect device to pair with this software.
https://github.com/skuep/AIOC

The AIOC also has a transistor to assert the PTT, so maybe that could be used instead of a serial command?

**Comment by nicsure** [comment]
I'd be more than happy to test the AOIC out if they'd send me one. As I don't own one I can't really support it.

**Comment by tristanmoney** [comment]
Please email me your address, I will order you some AIOC 's from JLCPCB.

**Comment by nicsure** [comment]
Thank you very much for that offer Tristan, I really appreciate your generosity. I've already had a viewer contact me and has sent one to me. Thank you again for that offer though, it really does mean so much to me that this community is so supportive.

**Comment by nicsure** [comment]
Just to be sure, you are unlocking the TX on the Dock interface aren't you? The top right button?

**Comment by tristanmoney** [comment]
I didn't know about that button! TX works fine once unlocked. Sorry I only
had 15 minutes to try it out, please close the issue.

**Comment by ErikS-web** [comment]
When the AIOC is plugged into the radio, can you listen to the audio from the radio ?
