### ISSUE TITLE
[FEATURE] XVFO: add VOX-button

### ISSUE THREAD

**Issue by ErikS-web** [nicsure/QuanshengDock#60]
Would like to have the `VOX`-button at XVFO-screen

**Comment by nicsure** [comment]
I was contemplating this, but it's kind of tricky. I'll see what I can come up with.

**Comment by nicsure** [comment]
This is not simple, you have VOX sensitivity, but you also don't want it going into transmit when you put your coffee down near the microphone and you don't want it keying down too quickly between pauses in speaking. That's 3 extra settings to deal with. Also I think it's prudent to automatically disable VOX on change of frequency.

**Comment by nicsure** [comment]
17q has VOX now, sensitivity can be adjusted in the settings. Night need a little tweaking though.

**Comment by ErikS-web** [comment]
it works, after some tuning 👍 

![VOX-settings](https://github.com/nicsure/QuanshengDock/assets/148579604/ca3c2a63-223e-49a3-8535-42893a0f8157)
![VOX-02](https://github.com/nicsure/QuanshengDock/assets/148579604/957594ca-4143-4fcf-972c-a57c7678a21f)
