### ISSUE TITLE
[BUG] XVFO Scanner - Blue lines,  after receiving a station - using a scan RANGE

### ISSUE THREAD

**Issue by ErikS-web** [nicsure/QuanshengDock#61]
QD 0.32.16q XVFO scanner mode,  using a scan **RANGE 2 meter** (144-160 Mhz)

When a channel is received, a purple line is drawn. AFTER 4 seconds, or as soon as the signal disappears, the scanner continues.
But, the trigger then draws a **_blue line on all channels afterwards_**, with the same signal strength, **_while nothing is received._**

![Knipsel](https://github.com/nicsure/QuanshengDock/assets/148579604/44598284-16dc-4948-9350-6cb41c9819ce)

**Comment by nicsure** [comment]
Yes I know about that one, it's because the whole range is treated as a single channel, so the signal history is being applied to all the frequencies in the range. I think probably removing the signal history bars for a range would be the easiest option.

**Comment by ErikS-web** [comment]
Yes, let's try to come up with a functional solution somewhere.

Because I do like the screen, also in mixed mode. Range(s) and specific frequencies 👍 

In this picture: Freq, Freq, Range, Freq

<img width="450" src="https://github.com/nicsure/QuanshengDock/assets/148579604/34ccfdbc-3460-48db-8cd2-f48d758d951c)" hspace="30" >

**Comment by nicsure** [comment]
This should be resolved next release.

**Comment by ErikS-web** [comment]
Published SOURCE code under rel 18 is version 17.

![Knipsel](https://github.com/nicsure/QuanshengDock/assets/148579604/41058ffd-ce65-41e0-aae1-09e264dbe28c)

**Comment by nicsure** [comment]
Yeah I forgot to sync before I compiled the release. The main branch is .18q though

**Comment by ErikS-web** [comment]
But look here... nice picture .... 👍 

![Knipsel](https://github.com/nicsure/QuanshengDock/assets/148579604/717d6770-7f9f-48b8-9c95-0f662188acc1)

**Comment by ErikS-web** [comment]
Yep... i compiled loaclly and it was 17 ???? That is how I detected.

Aha I now also see what is mentioned in release notes
![Knipsel](https://github.com/nicsure/QuanshengDock/assets/148579604/2e58329b-53bd-4936-8f5b-df4ddf427105)


![Knipsel](https://github.com/nicsure/QuanshengDock/assets/148579604/e6b23ec9-d81a-448b-97a6-30b0ca28d86b)

**Comment by ErikS-web** [comment]
Perhabs delete release 18 and insert it again on Github ?..

This issue can be closed. Scanning RANGE is now OK.
