### ISSUE TITLE
[BUG] XVFO - VOX timeout is not overruled by on-screen PTT (with mouse)

### ISSUE THREAD

**Issue by ErikS-web** [nicsure/QuanshengDock#62]
Version 18q

When FOX active the PTT is not always included to force state TX

I start talking and VOX becomes active (BLUE)
Then I press PTT  (with MOUSE) and stop talking
After some seconds the TX is OFF, while PTT is pressed. TX had to stay active

When using SPACE and not mouse on PTT it reactis different.
Goes to RX and direct back to TX

...

**Comment by nicsure** [comment]
You can use one or the other atm not both. When VOX is active it sends a key down request when it stops hearing. If you've pressed manual ptt that will not change it.

**Comment by nicsure** [comment]
As this is fixed, I'm closing it.
