### ISSUE TITLE
XVFO PTT on external microphone does not work.

### ISSUE THREAD

**Issue by PA2HJK** [nicsure/QuanshengDock#63]
The PTT on the external microphone is working with the UV-K5 docking software on the screen that shows the Quansheng display. But when i go to the XVFO the PTT on the microphone does not work anymore. Only the PTT button on the XVFO screen is working.
Is it possible to make the PTT on the external microphone working with the XVFO ?

**Comment by nicsure** [comment]
It's impossible for XVFO to work with an external microphone.

**Comment by PA2HJK** [comment]
OK. Thank you for the good explanation.

**Comment by nicsure** [comment]
Revision 2 of the passive adapter board may solve this however by sending the PTT signal over the unused stereo microphone audio channel. This is still very much vapour ware though.
