### ISSUE TITLE
[FEATURE]XVFO-scanning - Presets In List: Missing an option to DELETE 1 channel

### ISSUE THREAD

**Issue by ErikS-web** [nicsure/QuanshengDock#68]
Button DELETE deletes a `Scan List` (middle section)

There is no option to delete a channel inserted in the right screen-section ` Presets In List`

**Comment by nicsure** [comment]
Yeah there is, the "Remove" button bottom right.

I can add the delete key shortcut to delete  whatever is selected in the currently selected list.

**Comment by ErikS-web** [comment]
Oeps. of course.
