### ISSUE TITLE
This Quansheng Driver is not supported by Chirp?

### ISSUE THREAD

**Issue by MikeGriffinReborn** [nicsure/QuanshengDock#70]
I think the "egzumer" version might be dormant now that you have forked and moving forward, it's great firmware. However, I can no longer push to my radio via Chirp as it states the "Firmware" is not supported by the driver. I know you have your channel editor and "Dock" is rocking but Chirp can just do way more and I need to continue to use it.

I guess now I have to install the original "egzumer" firmware, push out via Chirp, and reinstall your driver ... ?

**Comment by nicsure** [comment]
And exactly what do you expect me to do about it?
