### ISSUE TITLE
Willing to Help ....

### ISSUE THREAD

**Issue by MikeGriffinReborn** [nicsure/QuanshengDock#71]
I posted the Chirp Question, sorry if I pushed your hot button ;) but seriously, I am a 20+ year .NET developer, you can see one of my projects here => [https://mikegriffinreborn.github.io/EntitySpaces/](https://mikegriffinreborn.github.io/EntitySpaces/) 

I work in .NET all day every day for work as well. If you like I could take the Channel Programming and flush it out and you could kiss "Chirp"requests goodbye forever ... Would love to help ...

- Mike

**Comment by nicsure** [comment]
You very much pressed my HOT button. This situation with CHIRP is ridiculous, it has been done deliberately. So what's going to happen? I'll tell you, a whole bunch of time and effort will be spent to get it to work, then, probably days later they'll "update" again and guess what? It'll stop working and I'll be flooded with people moaning about not being able to use the latest, greatest, we all must bow down, CHIRP God, and the cycle begins all over again. I won't play that game.
