### ISSUE TITLE
Not an Issue - Feature Question

### ISSUE THREAD

**Issue by infodungeon** [nicsure/QuanshengDock#76]
I suspect the answer is simply no as you would have already implemented it...
BUT is it possible to send audio from the PC over the cable?

Push-To-Talk and using the mic on the PC side would be a lovely feature for us computer geeks.
I'm guessing that there is no hook on the Quansheng firmware side for this.
If not, do you think it is something QS might be able to implement in firmware?

thanks,
Robert

**Comment by nicsure** [comment]
Using an interface such as the AIOC this is already possible and indeed supported in the software.
