### ISSUE TITLE
[Feature] Interacting with wsjt-x

### ISSUE THREAD

**Issue by troilus** [nicsure/QuanshengDock#77]
Dock controls PTT through the relevant data or signals provided by wsjt (used to implement automatic FT8 reception and transmission between wsjt and k5).

I have tried and implemented the following on pc:
- Radio's audio to wsjt-x.
- wsjt-x's audio is to radio through Dock.
- 
However, since VOX PTT of radio cannot be triggered when sql=0, so would it pissible to use Dock to receive wsjt-x commands to trigger the  PTT? 

Thanks!

**Comment by BranoSundancer** [comment]
Have you tried to use PTT COM port?
https://www.youtube.com/watch?v=tNXIOwoKMxg

**Comment by troilus** [comment]
Achieves with cec 0.3q
