### ISSUE TITLE
AIOC cable compatible?

### ISSUE THREAD

**Issue by waydenie** [nicsure/QuanshengDock#8]
Wondering if this was used with an AIOC device ( https://github.com/skuep/AIOC ) , would this be able to use usb audio devices on the PC , instead of the audio patch wiring?

**Comment by nicsure** [comment]
I have an AIOC on the way, so it should be supported soon hopefully.

**Comment by ErikS-web** [comment]
See (closed) issue #06

**Comment by waydenie** [comment]
Ah! thanks so much, I missed that one...

I finally found a few mins to find my AIOC, install the firmware and run the app with my AIOC. Runs great, as described in issue #6! thanks for this great software, I think this issue can be closed too!

**Comment by ErikS-web** [comment]
You should be able to close your issue yourself... See below

**Comment by waydenie** [comment]
Thanks again, this is a great project!
